services:
  backend-example:
    image: backend-example:latest
    build: .
    container_name: backend-example
    restart: unless-stopped
    ports:
      - 127.0.0.1:8080:8080
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 30s